apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: spike-phase2
  labels:
    app: notification-service
    service: notification
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        service: notification
        version: v1.0.0
    spec:
      containers:
      - name: notification-service
        image: spike/notification-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: REDIS_URL
          value: "redis://redis.spike-infrastructure:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: notification-service-url
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: amqp-url
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.spike-phase1:8001"
        # Email configuration
        - name: SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: smtp-server
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: smtp-port
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: smtp-password
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: from-email
        # SMS configuration
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: sms-credentials
              key: twilio-account-sid
              optional: true
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: sms-credentials
              key: twilio-auth-token
              optional: true
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: sms-credentials
              key: twilio-phone-number
              optional: true
        # Push notification configuration
        - name: FIREBASE_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: push-credentials
              key: firebase-server-key
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: templates
          mountPath: /app/src/templates
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: templates
        configMap:
          name: notification-templates
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: spike-phase2
  labels:
    app: notification-service
    service: notification
spec:
  selector:
    app: notification-service
  ports:
  - port: 8003
    targetPort: 8003
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-templates
  namespace: spike-phase2
data:
  grade_update_he.html: |
    <!DOCTYPE html>
    <html dir="rtl" lang="he">
    <head>
        <meta charset="utf-8">
        <title>{{ subject }}</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                text-align: right;
                direction: rtl;
            }
            .content {
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 8px;
            }
            .header {
                background-color: #f8f9fa;
                padding: 15px;
                border-radius: 5px;
                margin-bottom: 20px;
            }
            .grade {
                font-size: 24px;
                font-weight: bold;
                color: #28a745;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <div class="header">
                <h1>{{ subject }}</h1>
            </div>
            <p>{{ body }}</p>
            {% if data.course_name %}
                <p><strong>קורס:</strong> {{ data.course_name }}</p>
            {% endif %}
            {% if data.grade %}
                <p class="grade">ציון: {{ data.grade }}</p>
            {% endif %}
            <hr>
            <small>הודעה זו נשלחה מפלטפורמת ספייק האקדמית</small>
        </div>
    </body>
    </html>
  grade_update_en.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{{ subject }}</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }
            .content {
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 8px;
            }
            .header {
                background-color: #f8f9fa;
                padding: 15px;
                border-radius: 5px;
                margin-bottom: 20px;
            }
            .grade {
                font-size: 24px;
                font-weight: bold;
                color: #28a745;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <div class="header">
                <h1>{{ subject }}</h1>
            </div>
            <p>{{ body }}</p>
            {% if data.course_name %}
                <p><strong>Course:</strong> {{ data.course_name }}</p>
            {% endif %}
            {% if data.grade %}
                <p class="grade">Grade: {{ data.grade }}</p>
            {% endif %}
            <hr>
            <small>This message was sent from Spike Academic Platform</small>
        </div>
    </body>
    </html>

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: spike-phase2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70