name: Microservices CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'services/**'
      - 'k8s/**'
      - 'charts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/**'
      - 'k8s/**'
      - 'charts/**'

env:
  DOCKER_REGISTRY: registry.spike-platform.com
  KUBERNETES_NAMESPACE: spike-platform

jobs:
  # Test microservices
  test-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, tenant-service]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: services/${{ matrix.service }}/package-lock.json

    - name: Install dependencies
      working-directory: services/${{ matrix.service }}
      run: npm ci

    - name: Run type checking
      working-directory: services/${{ matrix.service }}
      run: npm run type-check

    - name: Run linting
      working-directory: services/${{ matrix.service }}
      run: npm run lint

    - name: Run unit tests
      working-directory: services/${{ matrix.service }}
      run: npm test

    - name: Run integration tests
      working-directory: services/${{ matrix.service }}
      run: npm run test:integration
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_password
        REDIS_HOST: localhost
        REDIS_PORT: 6379

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  # Security scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: test-services
    strategy:
      matrix:
        service: [auth-service, tenant-service]

    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'services/${{ matrix.service }}'
        format: 'sarif'
        output: 'trivy-results-${{ matrix.service }}.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results-${{ matrix.service }}.sarif'

  # Build and push Docker images
  build-images:
    runs-on: ubuntu-latest
    needs: [test-services, security-scan]
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: [auth-service, tenant-service]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: services/${{ matrix.service }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Contract testing between services
  contract-tests:
    runs-on: ubuntu-latest
    needs: test-services

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Pact dependencies
      run: npm install -g @pact-foundation/pact-cli

    - name: Run contract tests
      run: |
        # Start services for contract testing
        docker-compose -f docker-compose.test.yml up -d --build

        # Wait for services to be ready
        sleep 30

        # Run Pact tests
        cd tests/contracts
        npm ci
        npm run test:pact

        # Publish contracts if on main branch
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          npm run pact:publish
        fi

    - name: Cleanup
      if: always()
      run: docker-compose -f docker-compose.test.yml down

  # Deploy to staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-images, contract-tests]
    if: github.ref == 'refs/heads/main'
    environment: staging

    steps:
    - uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.28.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to staging
      run: |
        export KUBECONFIG=kubeconfig

        # Update Helm dependencies
        helm dependency update charts/spike-platform

        # Deploy to staging
        helm upgrade --install spike-platform-staging ./charts/spike-platform \
          --namespace staging \
          --create-namespace \
          --set global.imageRegistry=${{ env.DOCKER_REGISTRY }} \
          --set authService.image.tag=sha-${{ github.sha }} \
          --set tenantService.image.tag=sha-${{ github.sha }} \
          --set environment=staging \
          --wait \
          --timeout=10m

    - name: Run smoke tests
      run: |
        export KUBECONFIG=kubeconfig

        # Wait for services to be ready
        kubectl rollout status deployment/spike-platform-staging-auth-service -n staging
        kubectl rollout status deployment/spike-platform-staging-tenant-service -n staging

        # Run smoke tests
        cd tests/smoke
        npm ci
        npm run test:staging

  # Multi-tenant validation tests
  multi-tenant-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Run multi-tenant isolation tests
      run: |
        cd tests/multi-tenant
        npm ci
        npm run test:isolation
      env:
        TEST_ENVIRONMENT: staging
        BGU_TEST_CREDENTIALS: ${{ secrets.BGU_TEST_CREDENTIALS }}
        TAU_TEST_CREDENTIALS: ${{ secrets.TAU_TEST_CREDENTIALS }}

    - name: Run tenant provisioning tests
      run: |
        cd tests/multi-tenant
        npm run test:provisioning
      env:
        TEST_ENVIRONMENT: staging
        KUBERNETES_CONFIG: ${{ secrets.KUBE_CONFIG_STAGING }}

  # Performance testing
  performance-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup K6
      run: |
        wget https://github.com/grafana/k6/releases/download/v0.46.0/k6-v0.46.0-linux-amd64.tar.gz
        tar -xzf k6-v0.46.0-linux-amd64.tar.gz
        sudo mv k6-v0.46.0-linux-amd64/k6 /usr/local/bin/

    - name: Run performance tests
      run: |
        cd tests/performance
        k6 run --out json=results.json load-test.js
      env:
        TARGET_URL: https://staging.spike-platform.com

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: tests/performance/results.json

  # Deploy to production (manual approval)
  deploy-production:
    runs-on: ubuntu-latest
    needs: [multi-tenant-tests, performance-tests]
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.28.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Blue-Green Deployment
      run: |
        export KUBECONFIG=kubeconfig

        # Deploy to green environment
        helm upgrade --install spike-platform-green ./charts/spike-platform \
          --namespace production-green \
          --create-namespace \
          --set global.imageRegistry=${{ env.DOCKER_REGISTRY }} \
          --set authService.image.tag=sha-${{ github.sha }} \
          --set tenantService.image.tag=sha-${{ github.sha }} \
          --set environment=production \
          --set deployment.color=green \
          --wait \
          --timeout=15m

    - name: Production smoke tests
      run: |
        export KUBECONFIG=kubeconfig

        # Run production readiness tests
        cd tests/smoke
        npm run test:production-green

    - name: Switch traffic to green
      run: |
        export KUBECONFIG=kubeconfig

        # Update Istio VirtualService to route to green
        kubectl patch virtualservice spike-platform -n production \
          --type merge -p '{"spec":{"http":[{"route":[{"destination":{"host":"spike-platform","subset":"green"},"weight":100}]}]}}'

    - name: Cleanup blue deployment
      run: |
        export KUBECONFIG=kubeconfig

        # Wait 10 minutes for traffic to stabilize
        sleep 600

        # Delete blue deployment
        helm uninstall spike-platform-blue -n production-blue || true
        kubectl delete namespace production-blue || true

    - name: Update production with new blue
      run: |
        export KUBECONFIG=kubeconfig

        # Rename green to blue for next deployment
        kubectl patch virtualservice spike-platform -n production \
          --type merge -p '{"spec":{"http":[{"route":[{"destination":{"host":"spike-platform","subset":"blue"},"weight":100}]}]}}'